Repository Abroady-Official/Abroady-Server, pull requests merged in 2022-07, with the labels that each got.

#2 게시글 CRUD 추가
  src/app.module.ts
  src/modules/posts/dto/posts-post.req.dto.ts
  src/modules/posts/dto/posts-put.params.dto.ts
  src/modules/posts/posts.controller.ts
  src/modules/posts/posts.module.ts
  src/modules/posts/posts.service.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#4 [feature/#1] 게시글 CRUD 추가
  src/app.module.ts
  src/modules/posts/dto/posts-post.req.dto.ts
  src/modules/posts/dto/posts-put.params.dto.ts
  src/modules/posts/posts.controller.ts
  src/modules/posts/posts.module.ts
  src/modules/posts/posts.service.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#6 테이블 수정
  prisma/schema.prisma
  src/common/constants/responseMessage.ts
  src/modules/posts/dto/posts-post.req.dto.ts
  src/modules/posts/posts.controller.ts
  src/modules/posts/posts.service.ts
Labels: 🔧 Fix, 🐻‍❄️ 혁준 🐻‍❄️

#8 카테고리 관련 기능 추가
  prisma/schema.prisma
  src/app.module.ts
  src/modules/categories/categories.controller.ts
  src/modules/categories/categories.module.ts
  src/modules/categories/categories.service.ts
  src/modules/posts/dto/posts-get-category.params.dto.ts
  src/modules/posts/posts.controller.ts
  src/modules/posts/posts.service.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#10 CI/CD 설정 추가
  scripts/after-deploy.sh
Labels: 🌏 Deploy, 🐻‍❄️ 혁준 🐻‍❄️

#13 게시글 상세 조회 추가
  src/common/constants/responseMessage.ts
  src/common/swagger.ts
  src/modules/posts/dto/posts-get.params.dto.ts
  src/modules/posts/posts.controller.ts
  src/modules/posts/posts.service.ts
Labels: ✨ Feature, 🐻‍❄️ 혁준 🐻‍❄️

#15 소셜 로그인/회원가입 API 작성
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  prisma/schema.prisma
  src/app.module.ts
  src/common/constants/index.ts
  src/common/constants/swagger/domain/auth/AuthTokenGetAccepted.ts
  src/common/constants/swagger/domain/auth/AuthTokenGetSuccess.ts
  src/common/constants/tokenValidationType.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/common/auth.strategy.ts
  src/modules/auth/common/auth.type.ts
  src/modules/auth/config/auth.config.ts
  src/modules/auth/dto/auth-post.req.dto.ts
  src/modules/auth/dto/auth-post.res.dto.ts
  src/modules/auth/dto/auth-signin.res.dto.ts
  src/modules/auth/dto/auth-token-get.res.dto.ts
  src/modules/auth/dto/auth.param.dto.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/users/dto/user.dto.ts
Labels: ✨ Feature
